### ISSUE TITLE
HealthDto doesn't include enough information for Jackson

### ISSUE THREAD

**Issue by bbaugher** [cerner/beadledom#67] opened 2017-12-15 17:01 UTC
When attempting to use `AvailabilityResource` or `HealthResource` with a client it fails with,

`com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of com.cerner.beadledom.health.dto.HealthDto, problem: abstract types either need to be mapped to concrete types, have custom deserializer, or be instantiated with additional type information`

This looks to be because `HealthDto` is an AutoValue class and Jackson is missing the connection between `HealthDto` and the implementation AutoValue class `AutoValue_HealthDto`.

**Comment by johnlcox** [comment] 2017-12-15 17:05
It looks like the problem is that all AutoValue DTOs should be annotated with `@JsonDeserialize(builder = <abstractClassName>.Builder.class)`, and the builder may also need the `JsonPojoBuilder` annotation.

**Comment by bbaugher** [comment] 2017-12-15 17:06
Heres an example I followed for AutoValue + Jackson using builders, https://github.com/artem-zinnatullin/AutoJackson#okay-im-in-show-me-the-code

**Comment by nathanschile** [comment] 2018-07-18 14:50
Fixed with PR #100

**Closed by nathanschile** 2018-07-18 14:50 UTC
Labels: bug
